
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keys
spec:
  provider: azure
  secretObjects:                             
  - data:
    - key: postgres-url                          
      objectName: postgres-url     
    - key: postgres-user                          
      objectName: postgres-user
    - key: postgres-pass                          
      objectName: postgres-pass                      
    secretName: dbsecret                    
    type: Opaque  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "90e35a2c-3a2e-495a-88a6-9ca1cd5d710a"
    keyvaultName: "andy-cert-keyvault"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: postgres-url
          objectType: secret                       # object types: secret, key or cert
          objectVersion: ""                     # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: postgres-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-pass
          objectType: secret
          objectVersion: "" 
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"


# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-sync
# spec:
#   provider: azure                             
#   secretObjects:                             
#   - data:
#     - key: postgres-url                          
#       objectName: postgres-url     
#     # - key: postgres-user                          
#     #   objectName: postgres-user
#     # - key: postgres-pass                          
#     #   objectName: postgres-pass                      
#     secretName: dbsecret                    
#     type: Opaque                             